# Generated by Django 5.1.7 on 2025-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dater_joined',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
