# Generated by Django 5.2 on 2025-05-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghour',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
