# Generated by Django 5.2 on 2025-05-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Prize',
        ),
    ]
