# Generated by Django 5.2 on 2025-05-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0002_openinghour_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghour',
            name='test',
        ),
    ]
