# Generated by Django 5.2 on 2025-05-02 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0002_delete_user_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_number', models.PositiveIntegerField()),
                ('prize_name', models.CharField(max_length=100)),
                ('prize_description', models.TextField()),
                ('prize_image', models.ImageField(blank=True, null=True, upload_to='prize_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
