# Generated by Django 5.2 on 2025-05-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0003_user_prize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Prize',
        ),
    ]
