# Generated by Django 5.1.7 on 2025-05-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
