# Generated by Django 5.2 on 2025-05-02 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0004_delete_user_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=20)),
                ('from_date', models.DateField()),
                ('due_date', models.DateField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('car_rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivequest.car_rental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
