# Generated by Django 5.2 on 2025-05-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
