# Generated by Django 5.2 on 2025-04-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0005_car_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_rental',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
