# Generated by Django 5.2 on 2025-04-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0006_car_rental_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='XP',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
