# Generated by Django 5.2 on 2025-05-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0006_openinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='test',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
