# Generated by Django 5.2 on 2025-05-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0007_openinghours_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='test',
        ),
    ]
