# Generated by Django 5.2 on 2025-04-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0007_user_xp_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_rental',
            name='payment_method',
            field=models.CharField(choices=[('None', 'None'), ('Cash', 'Cash'), ('PayPal', 'PayPal'), ('Credit Card', 'Credit Card')], default='None', max_length=11),
        ),
    ]
