# Generated by Django 5.2 on 2025-05-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0008_remove_openinghours_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningHours',
            new_name='OpeningHour',
        ),
    ]
