# Generated by Django 5.2 on 2025-04-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0008_car_rental_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
