# Generated by Django 5.1.7 on 2025-04-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stars',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
