# Generated by Django 5.1.7 on 2025-04-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0011_user_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rent_center_images/')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
