# Generated by Django 5.1.7 on 2025-04-26 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0012_rentalcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Electric', 'Electric'), ('Convertible', 'Convertible'), ('Hybrid', 'Hybrid'), ('Sports', 'Sports'), ('Luxury', 'Luxury'), ('Pickup', 'Pickup')], default='Unknown', max_length=14),
        ),
        migrations.AddField(
            model_name='car',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivequest.rentalcenter'),
        ),
    ]
