# Generated by Django 5.1.7 on 2025-04-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0013_car_car_type_car_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='times_rated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
    ]
