# Generated by Django 5.2 on 2025-04-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0015_remove_car_times_rated_remove_car_total_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prizes1',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='prizes2',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='prizes3',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='prizes4',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='prizes5',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
