# Generated by Django 5.1.7 on 2025-04-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0015_remove_car_times_rated_remove_car_total_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prize1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='prize2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='prize3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='prize4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='prize5',
            field=models.BooleanField(default=False),
        ),
    ]
