# Generated by Django 5.2 on 2025-04-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0016_user_prizes1_user_prizes2_user_prizes3_user_prizes4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prizes1',
            new_name='prize1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='prizes2',
            new_name='prize2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='prizes3',
            new_name='prize3',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='prizes4',
            new_name='prize4',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='prizes5',
            new_name='prize5',
        ),
    ]
