# Generated by Django 5.2 on 2025-04-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequest', '0017_rename_prizes1_user_prize1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prize1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='prize2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='prize3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='prize4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='prize5',
            field=models.BooleanField(default=False),
        ),
    ]
